import type { Metadata } from "next";
import { figTree, inter } from "@/fonts/fonts";
import "./globals.css";
import Container from "@/components/common/Container";
import Navbar from "@/components/shared/Navbar";
import Footer from "@/components/shared/Footer";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={`${figTree.variable} ${inter.variable}`}>
        <Container>
          <Navbar />
          {children}
          <Footer/>
        </Container>
      </body>
    </html>
  );
}
